service: wanderley-bot

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:ssm:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":parameter/telegramToken"
functions:
  wanderley:
    handler: wanderley.lambda_handler
    events:
      - http: POST /

plugins:
  - serverless-python-requirements
